services:
  ak0:
    container_name: ak0
    image: ak0
    profiles: ["no-grafana", "full"]
    user: 65532:65532
    restart: unless-stopped
    ports:
      - 8200:8200
    environment:
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4318/v1/metrics
      - OTEL_RESOURCE_ATTRIBUTES="service.name=ak0,service.version=0.0.1"
    depends_on:
      - prometheus
    networks:
      - default-network

  otelcol:
    container_name: otelcol_ak0
    image: otel/opentelemetry-collector-contrib:0.119.0
    profiles: ["no-grafana", "full"]
    user: 10001:10001
    restart: unless-stopped
    environment:
      - BASIC_AUTH=${BASIC_AUTH}
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - default-network
  
  prometheus:
    container_name: prometheus_ak0
    image: prom/prometheus:v3.1.0
    profiles: ["no-grafana", "full"]
    user: 65534:65534
    command: --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/prometheus_web_config.yaml --web.enable-otlp-receiver
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus_web_config.yaml:/etc/prometheus/prometheus_web_config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 9090:9090
    networks:
      - default-network

  grafana:
    container_name: grafana_ak0
    image: grafana/grafana-oss:11.5.1
    profiles: ["full"]
    user: 472:472
    restart: unless-stopped
    environment:
      - BASIC_AUTH=${BASIC_AUTH}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GRAFANA_BASIC_AUTH=${GRAFANA_BASIC_AUTH}
      - GRAFANA_PROMETHEUS_DATASOURCE_URL=http://prometheus:9090
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafana.ini:/etc/grafana/grafana.ini
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 3000:3000
    networks:
      - default-network
    depends_on:
      - prometheus

volumes:
  grafana-data: {}
  prometheus-data: {}

networks:
  default-network:
    driver: bridge
