receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      # grpc:
      #   endpoint: 0.0.0.0:4317

processors:
  # todo: add memory limiter
  batch:
      timeout: 10s
      send_batch_size: 100

exporters:
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true  # todo: set to false and configure certs
    headers:
      # add here eg
      # Authorization: "Bearer <token>"

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
