apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
prune: true

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    # uid: my_unique_uid
    url: https://prometheus:9090
    # <bool> Enables basic authorization.
    basicAuth: true
    # <string> Sets the basic authorization username.
    basicAuthUser: admin
    # <bool> Enables credential headers.
    withCredentials: true
    isDefault: true
    # <map> Fields to convert to JSON and store in jsonData.
    jsonData:
      httpMethod: POST
      # manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      tlsAuth: true
      tlsAuthWithCACert: true
    # <map> Fields to encrypt before storing in jsonData.
    secureJsonData:
      # <string> Defines the CA cert, client cert, and
      # client key for encrypted authentication.
      tlsCACert: $__file{/etc/grafana/ak0_ca.crt}
      tlsClientCert: $__file{/etc/grafana/grafana.crt}
      tlsClientKey: $__file{/etc/grafana/grafana.key}
      # <string> Sets the basic authorization password.
      basicAuthPassword: $GRAFANA_BASIC_AUTH
    # <int> Sets the version. Used to compare versions when
    # updating. Ignored when creating a new data source.
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: true
