receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      # grpc:
      #   endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 300

  batch:
      timeout: 10s
      send_batch_size: 100

exporters:
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: http://prometheus:9090/api/v1/otlp
    # tls:
      # insecure: true
      # cert_file: /etc/ssl/certs/otel.crt
      # key_file: /etc/ssl/certs/private/otel.key
      # ca_file: /etc/ssl/certs/ak0_ca.crt
      # insecure_skip_verify: true
    headers:
      Authorization: "Basic ${BASIC_AUTH}"

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
