# Usernames and hashed passwords that have full access to the web
# server via basic authentication. If empty, no basic authentication is
# required. Passwords are hashed with bcrypt.
basic_auth_users:
  admin: $2b$12$2iIKK/7f3h8Gmev57pzP1u4xqfsp6jnNBoF7EmGMCcR2E4BK6ESDy

